name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Cache browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-browsers-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run pw:test --shard=${{ matrix.shard }}:2
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright/report/
          retention-days: 30
  merge-playwright-reports:
    name: Merge Playwright Reports
    if: ${{ always() }}
    needs: [test-playwright]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache npm and browsers
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-npm-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-browsers-
      - name: Download playwright artifacts    
        uses: actions/download-artifact@v3
        with:
          name: playwright-report-1
      - uses: actions/download-artifact@v3
        with:
          name: playwright-report-2
      - uses: actions/download-artifact@v3
        with:
          name: playwright-report-3
      - uses: actions/download-artifact@v3
        with:
          name: playwright-report-4

      - name: Download playwright-merge-html-reports
        run: npm install playwright-merge-html-reports --dev
      - name: Run Report Merge
        run: npm run merge-reports
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: combined-report
          path: playwright-report-folder/
  publish-merged-report:
    name: Publish Merged Report
    needs: [merge-playwright-reports]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download combined report
      uses: actions/download-artifact@v2
      with:
        name: combined-report
        path: .

    - name: Rename and upload artifact
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        mv combined-report/index.html index_${PR_NUMBER}.html
        echo "Renamed index.html to index_${PR_NUMBER}.html"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        enable_jekyll: false
        
