name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Cache browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-browsers-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run pw:test --shard=${{ matrix.shard }}:2
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright/report/
          retention-days: 30

  merge:
    name: Merge Reports
    if: ${{ always() }}
    needs: [test]
    timeout-minutes: 60
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - name: Download Merge HTML
        run: npm install playwright-merge-html-reports --dev
      - name: Run Report Merge
        run: npm run merge-reports
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: combined-report
          path: playwright-report-folder/
          retention-days: 3
      - name: Print PR event
        run: echo "PR Number is ${{ github.event }}"

  deploy:
    name: Deploy to GitHub Pages
    if: ${{ always() }}
    needs: [merge]
    timeout-minutes: 60
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Fetch all history
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install PageCrypt
        run: npm install pagecrypt --save-dev
      - uses: actions/download-artifact@v3
        with:
          name: combined-report
          path: ./reports/PR${{ github.event.pull_request.number }}
      - name: Create/Update PR folder and dummy index.html
        run: |
          mkdir -p "./reports/PR${{ github.event.pull_request.number }}"
          echo "<h1>Hello, World!</h1>" > "./reports/PR${{ github.event.pull_request.number }}/index.html"
      - name: Protect index.html with PageCrypt
        run: npx pagecrypt "./reports/PR${{ github.event.pull_request.number }}/index.html" "./reports/PR${{ github.event.pull_request.number }}/index.html" ${{ secrets.PAGECRYPT_PASSWORD }}
      - name: Copy report to temporary directory
        run: |
          mkdir temp
          cp -r ./reports/* temp/
      - name: Checkout gh-pages
        run: |
          git fetch origin
          git checkout gh-pages --force
      - name: Move files from temporary directory to working directory
        run: |
          cp -r ./temp/* .
      - name: Configure Git
        run: |
          git config user.name "andrej.kanuch"
          git config user.email "andrej.kanuch@sudolabs.io"
      - name: Commit and Push to gh-pages
        run: |
          git add .
          git commit -m "Update Playwright tests results PR${{ github.event.pull_request.number }}"
          git push origin gh-pages
